spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_db
    username: local_user
    password: local_password
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration/local  # 로컬 전용 마이그레이션 포함