spring:
  datasource:
    url: jdbc:mysql://dev-db-server:3306/dev_db
    username: dev_user
    password: dev_password
  flyway:
    enabled: true
    locations: classpath:db/migration  # 공통 마이그레이션만 사용